Feature/create crystal knows pod
team-hercules-ivs/CrystalKnowsPodTEMP pull request #1
Opened 2024-04-16 20:17 UTC by JTackettIVS

Created Crystal Knows pages for ConnectWise Pods

2024-04-17 12:41 UTC, IDelgadoIvs commented on Services/CrystalKnowsApi.cs
> +        public CrystalKnowsApi(HttpClient httpClient, IConfiguration configuration)
HttpClient httpClient is not being used but still in the consrtructor

2024-04-17 17:17 UTC, IDelgadoIvs requested changes
Review comments.

2024-04-17 17:17 UTC, IDelgadoIvs commented on Services/ConnectwiseApiConfiguration.cs
Do you think we need a whole seperate class for api config?  sems like we only need the url and clientid which are easily gotten in the environment variables/appsettings file.  The keys should be in the keyvault.  

this can probably be moved to the connectwiseapi class.  and have a method for getheaders.  

also we shouldnt need to use if (environment == "Development") when its run locally it should be using your local settings file.  and when it runs in production it knows to use the environment variables.   The public and private key in connectwise are the same are they not since the databases are synced.  so you can probably just use the keyvault and same key for both training and production. and use DI and program.cs to configure

2024-04-18 20:26 UTC, JTackettIVS commented on Services/CrystalKnowsApi.cs
> +                if (restParameters.Email == null && restParameters.LinkedInUrl == null)
Either LinkedIn URL or email is required to get the profile.  We can successfully get a profile off one of those 2 even if the name was somehow null.

2024-04-18 20:29 UTC, IDelgadoIvs commented on Services/CrystalKnowsApi.cs
> +                if (restParameters.Email == null && restParameters.LinkedInUrl == null)
Gotcha.

2024-04-22 18:48 UTC, JTackettIVS commented
Closing PR.  Creating new WASM project to move existing code to.  Will submit new PR with updated code.

2024-04-22 18:48 UTC, closed without merging